CREATE TABLE IF NOT EXISTS app_config (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    language TEXT NOT NULL,
    default_account_id TEXT NULL,
    mark_as_read_on_open INTEGER NOT NULL DEFAULT 1,
    show_snippets INTEGER NOT NULL DEFAULT 1,
    auto_load_images INTEGER NOT NULL DEFAULT 0,
    include_signature_in_replies INTEGER NOT NULL DEFAULT 1,
    request_read_receipts INTEGER NOT NULL DEFAULT 0,
    undo_send_delay_seconds INTEGER NOT NULL DEFAULT 5,
    launch_at_login INTEGER NOT NULL DEFAULT 1,
    check_for_updates INTEGER NOT NULL DEFAULT 1,
    minimize_to_tray INTEGER NOT NULL DEFAULT 0,
    theme TEXT NOT NULL DEFAULT 'system',
    font_size INTEGER NOT NULL DEFAULT 16,
    layout_mode TEXT NOT NULL DEFAULT 'split',
    density TEXT NOT NULL DEFAULT 'comfortable',
    thread_panel_width INTEGER NOT NULL DEFAULT 58,
    notifications_enabled INTEGER NOT NULL DEFAULT 1,
    notification_sound INTEGER NOT NULL DEFAULT 1,
    notification_scope TEXT NOT NULL DEFAULT 'inbox',
    quiet_hours_start TEXT NOT NULL DEFAULT '',
    quiet_hours_end TEXT NOT NULL DEFAULT '',
    developer_tools_enabled INTEGER NOT NULL DEFAULT 0,
    log_level TEXT NOT NULL DEFAULT 'info'
);

INSERT INTO app_config (
    id,
    language,
    default_account_id,
    mark_as_read_on_open,
    show_snippets,
    auto_load_images,
    include_signature_in_replies,
    request_read_receipts,
    undo_send_delay_seconds,
    launch_at_login,
    check_for_updates,
    minimize_to_tray,
    theme,
    font_size,
    layout_mode,
    density,
    thread_panel_width,
    notifications_enabled,
    notification_sound,
    notification_scope,
    quiet_hours_start,
    quiet_hours_end,
    developer_tools_enabled,
    log_level
) VALUES (
    1,
    'English',
    NULL,
    1,
    1,
    0,
    1,
    0,
    5,
    1,
    1,
    0,
    'system',
    16,
    'split',
    'comfortable',
    58,
    1,
    1,
    'inbox',
    '',
    '',
    0,
    'info'
)
ON CONFLICT(id) DO NOTHING;
